### ISSUE TITLE
Docker Container Not Populating Metrics - Login Error

### ISSUE THREAD

**Issue by vasugupta32** [prezhdarov/vmware-exporter#1]
I am encountering an issue with the vmware-exporter Docker container. The container starts successfully, but it does not populate any metrics and logs the following error:

```
ts=2024-08-05T05:29:26.248Z caller=vmware-exporter.go:71 level=debug disableexportertargetis=false
ts=2024-08-05T05:29:26.248Z caller=vmware.go:53 level=info msg="Loading VMware vSphere API"
ts=2024-08-05T05:29:26.248Z caller=vmware.go:19 level=info msg="Loading VMware vSphere collector set"
ts=2024-08-05T05:29:26.248Z caller=collector.go:118 level=debug msg="Collector vm is enabled"
ts=2024-08-05T05:29:26.248Z caller=collector.go:118 level=debug msg="Collector cluster is enabled"
ts=2024-08-05T05:29:26.248Z caller=collector.go:118 level=debug msg="Collector datacenter is enabled"
ts=2024-08-05T05:29:26.248Z caller=collector.go:118 level=debug msg="Collector datastore is enabled"
ts=2024-08-05T05:29:26.248Z caller=collector.go:114 level=debug msg="Collector esxcli.host.nic is disabled"
ts=2024-08-05T05:29:26.248Z caller=collector.go:114 level=debug msg="Collector esxcli.storage is disabled"
ts=2024-08-05T05:29:26.248Z caller=collector.go:118 level=debug msg="Collector host is enabled"
ts=2024-08-05T05:29:26.248Z caller=vmware-exporter.go:92 level=info msg="listening on" address=:9169
ts=2024-08-05T05:29:26.261Z caller=tls_config.go:313 level=info msg="Listening on" address=0.0.0.0:9169
ts=2024-08-05T05:29:26.261Z caller=tls_config.go:316 level=info msg="TLS is disabled." http2=false address=0.0.0.0:9169
ts=2024-08-05T05:30:04.010Z caller=collect.go:19 level=error msg="Login failed" target=null err="login err: Post \"https:///sdk\": http: no Host in request URL"
```

Metrics Observed:

When querying the /metrics endpoint, the following metrics are available:

`
 HELP promhttp_metric_handler_errors_total Total number of internal errors encountered by the promhttp metric handler.
 TYPE promhttp_metric_handler_errors_total counter
promhttp_metric_handler_errors_total{cause="encoding"} 0
promhttp_metric_handler_errors_total{cause="gathering"} 0
 HELP vmware_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which vmware_exporter was built, and the goos and goarch for the build.
 TYPE vmware_exporter_build_info gauge
`

Details:

I am using the following Docker run command:

```
docker run --network host -d --name vmware-exporter \
    -e VMWARE_VCENTER=http://your-vcenter-url \
    -e VMWARE_USERNAME=your-username \
    -e VMWARE_PASSWORD='your-password' \
    -e VMWARE_SSL=true \
    -e COLLECTOR_CLUSTER=true \
    -e COLLECTOR_DATACENTER=true \
    -e COLLECTOR_DATASTORE=true \
    -e COLLECTOR_HOST=true \
    -e COLLECTOR_VM=true \
    -e COLLECTOR_ESXCLI_HOST_NIC=true \
    -e COLLECTOR_ESXCLI_STORAGE=true \
    prezhdarov/vmware-exporter:latest
```
Expected Behavior:

The container should successfully connect to the VMware vCenter server and populate metrics, which can then be accessed via the /metrics endpoint.

Actual Behavior:

The container logs a "Login failed" error indicating a problem with the URL or login process. The metrics endpoint shows only the build info without any collected metrics.

Additional Information:

Ensure the vCenter URL is correctly set.
Validate that the username and password are correct.
Check if the SSL setting matches the vCenter configuration.
Verify if the correct collectors are enabled.
Please let me know if there are any additional configurations or changes needed to resolve this issue. Thank you!

**Comment by Gum97** [comment]
sampe problem

**Comment by prezhdarov** [comment]
Sorry guys, didn't expect anyone would ever use this, but I can see your frustration and where your problem is. 
You need to enable environment variables (same as VictoriaMetrics configuration, where I've borrowed the config from). To do this add those args to your startup:
```
-envflag.enable=true 
-envflag.prefix=vmw_
```
Then you can have env variables like:
```
vmw_log_level=info
vmw_vmware_password: 
vmw_vmware_username:
```
and so on. 

Oh, and you don't need to enable every single collector. All except the esxcli ones are enabled by default. ESXCli ones are disbled as they usually take longer to process - these execute actual esxcli commands on each and every host in vCenter to gather some otherwise unavailable information that I need and is not even in these dashboards, hence why disabled by default. You are free to try and use them if you like. All you need to run the collector is:
```
vmw_vmware_vcenter=
vmw_vmware_username=
vmw_vmware_password=
```
Or you can put everything in a yaml file - i.e. when you need an init container to build your configuration (as I do):
```yaml
vmware.vcenter: your_vcenter_fqdn
vmware.username: your_readonly_vcenter_user
vmware.password: your_password
```
and even add any other option you need. Then pass it to the exporter with --file. 

Hope this helps and if you have any questions - promise to read this more often!

**Comment by Gum97** [comment]
Thank you for your response. I will try your suggestions.

**Comment by vasugupta32** [comment]
Thank you for your response @prezhdarov , I tried, and It worked, Thanks.

**Comment by prezhdarov** [comment]
Glad it worked and sorry I didn't respond earlier.

**Comment by vasugupta32** [comment]
No worries, Thanks
